language: java

sudo: false

env:
  global:
#  - CODECOV_TOKEN="" TODO

script: "mvn cobertura:cobertura"

after_success:
- bash <(curl -s https://codecov.io/bash)

notifications:
  emails:
    recipients:
      -guillaume.falourd@zup.com.br
    on_success: always
    on_failure: always